language: node_js
node_js:
    - "0.10.17"
script: "grunt node:test"
services:
  - mongodb
before_script:
  - npm install -g grunt-cli
  - gem install sass

# whitelist
branches:
    only:
        - master
